### ISSUE TITLE
Design and build the Demo

### ISSUE THREAD

**Issue by rtorres678** [rtorres678/Senior-Design-Project#19]
Start as small as possible. Use an arduino or other microcontroller.

References:
- https://www.instructables.com/id/Upright-Laser-Harp/
- https://www.instructables.com/id/13-Note-MIDI-Laser-Harp-Controlled-by-Arduino/
- http://www.jbumstead.com/laser-harp.html

**Comment by username-takened** [comment]
Time estimate: 15 hr
