### ISSUE TITLE
Complete Charter

### ISSUE THREAD

**Issue by rtorres678** [rtorres678/Senior-Design-Project#2]
- [x]  Front Page---------------------------------------------------------------------------------Rabinson

- [x]  Vision--------------------------------------------------------------------------------------Rabinson
- [x]  Mission------------------------------------------------------------------------------------Anish
- [x]  Success Criteria---------------------------------------------------------------------------Anish
- [x]  Background-------------------------------------------------------------------------------Nik
- [x]  Related Work------------------------------------------------------------------------------Nik
- [x]  System Overview--------------------------------------------------------------------------Roberto
- [x]  Roles & Resp.------------------------------------------------------------------------------Roberto
- [x]  Cost Proposal------------------------------------------------------------------------------Raul
- [x]  Facilities & Equipment---------------------------------------------------------------------Raul
- [x]  Assumptions-------------------------------------------------------------------------------Amir
- [x]  Constraints---------------------------------------------------------------------------------Amir
- [x]  Risks ---------------------------------------------------------------------------------------Amir
- [x]  References -------------------------------------------------------------------------------All
- [x]  Documentation & Reporting--------------------------------------------------------------All
- [x]  ______Major Doc. Deliverables
- [x]  ______Recurring Sprint Items
- [x]  ______Closeout Materials

**Comment by username-takened** [comment]
Front page and vison

**Comment by raujimenez** [comment]
Cost Proposal and facilities and Equipment
Estimated: 3 hours
Actual: 3 hours

**Comment by Yanis091** [comment]
hey i took mission statement and success criteria - 2 hrs
Also, i edited/updated the og comment, feel free to update/change

**Comment by username-takened** [comment]
Front Page .... September 21 -------> 11 min
Vision ............. September 22 -------> 51 min

**Comment by Yanis091** [comment]
mission statement ----  9/20 ------ 30 min
success criteria --------  9/20 ------ 30 min

**Comment by Amir27060** [comment]
assumptions--9/23----30 mins
constraints ---9/23----30 mins
risks-----------9/23------1.5 hrs
