### ISSUE TITLE
Create list of possible components and research prices 

### ISSUE THREAD

**Issue by rtorres678** [rtorres678/Senior-Design-Project#4]
Identify common components and find price for them.

**Comment by raujimenez** [comment]
5 hours

**Comment by raujimenez** [comment]
Addition of 3 builds took 1.5 hour

Link to the spreadsheet:
https://docs.google.com/spreadsheets/d/1WZ93RuiGsNGewf0VeSlr9XBw3Pvjrf13P0M57N_7VJs/edit?usp=sharing
