### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by rtorres678** [rtorres678/Senior-Design-Project#5]
After voting on team name by 9/18
Team logo drafts done by 10/4 - 10/11

**Comment by username-takened** [comment]
1 hour

**Comment by username-takened** [comment]
Logo ………….. September 20 -------> 2:46 pm - 3:50 pm (1 hr 4 min)
Logo ......……... September 21 -------> 10:12 am - 12:37 pm (2 hr 25 min)
