### ISSUE TITLE
Create group name and project name

### ISSUE THREAD

**Issue by rtorres678** [rtorres678/Senior-Design-Project#6]
Leave a comment with your idea for a project name and a group name. We will vote when everyone has done so.

**Comment by raujimenez** [comment]
Suggestion:
  Project Name: ModuLaser or ModuLazer
  Group Name: Point Zero, FlashBeam

**Comment by Yanis091** [comment]
Project : Lights out / Beam it up /.wav / lazercraft / follow the light / lazer fiddle / pewpew gadget
Group : lightheads / resonance / distorted waves / synth Jedi / master blasters

**Comment by nikpurohit** [comment]
Project Name: LazerSynth / L-Synth
Group Name: Team Lazer / T-Lazer / Lazer Sense / L-Sense

**Comment by username-takened** [comment]
Project Name: LTunes; 
Group Name: LaserTeam;

**Comment by Amir27060** [comment]
Project Name: Lazer X, LaserZone , Laser Symphony
Group Name: Laser Crew,
